// angular/f-services/src/app/components/contactlist.component.ts
import {Component,OnInit} from '@angular/core';
import {Contact} from '../models/contact.model';
import {ContactService} from '../services/contactservice.service';

@Component({
	selector:"contact-list",
	templateUrl:"./contactlist.component.html"
})
export class ContactList implements OnInit {
	
	contact:Contact = new Contact("","","","",0);
	contactList:Contact[]=[];
	
	constructor(private _contactService:ContactService) {}
	
	ngOnInit() {
		this.getList();
	}
	
	getList() {
		this.contactList = this._contactService.getList();
	}
	
	addToList() {
		this._contactService.addToList(this.contact);
		this.contact = new Contact("","","","",0);
		this.getList();
	}
	
	removeFromList(id:number) {
		this._contactService.removeFromList(id);
		this.getList();
	}
}
<form (ngSubmit)="addToList()" #contactForm="ngForm">
	<label for="firstname">First name</label>
	<input type="text"
			id="firstname"
			name="firstname"
			[(ngModel)]="contact.firstname"/>
	<br/>
	<label for="lastname">Last name</label>
	<input type="text"
			id="lastname"
			name="lastname"
			[(ngModel)]="contact.lastname"/>
	<br/>
	<label for="email">Email</label>
	<input type="email"
			id="email"
			name="email"
			[(ngModel)]="contact.email"/>
	<br/>
	<label for="phone">Phone</label>
	<input type="tel"
			id="phone"
			name="phone"
			[(ngModel)]="contact.phone"/>
	<br/>
	<input type="submit" value="New Contact"/>
</form>
<table>
	<thead>
		<tr>
			<th>First name</th>
			<th>Last name</th>
			<th>Email</th>
			<th>Phone</th>
			<th>Remove</th>
		</tr>
	</thead>
	<tbody>
		<tr *ngFor="let c of contactList">
			<td>{{c.firstname}}</td>
			<td>{{c.lastname}}</td>
			<td>{{c.email}}</td>
			<td>{{c.phone}}</td>
			<td><button (click)="removeFromList(c.id)">Remove</button></td>
		</tr>	
	</tbody>
</table>

// react/05_lists/src/components/ContactList.js
import {useState} from 'react';

const ContactList = (props) => {
	
	const [state,setState] = useState({
		removeIndex:-1,
		editIndex:-1,
		firstname:"",
		lastname:"",
		email:"",
		phone:""
	});
	
	const changeToRemoveMode = (index) => {
		setState({
			...state,
			removeIndex:index,
			editIndex:-1
		})
	}

	const changeToEditMode = (index,contact) => {
		setState({
			firstname:contact.firstname,
			lastname:contact.lastname,
			email:contact.email,
			phone:contact.phone,
			removeIndex:-1,
			editIndex:index
		})
	}
	
	const onChange = (event) => {
		setState((state) => {
			return {
				...state,
				[event.target.name]:event.target.value
			}
		})
	}
	
	const cancel = () => {
		setState({
			removeIndex:-1,
			editIndex:-1,
			firstname:"",
			lastname:"",
			email:"",
			phone:""
		})
	}
	
	const removeContact = (id) => {
		props.removeContact(id);
		cancel();
	}

	const editContact = (contact) => {
		props.editContact(contact);
		cancel();
	}

	let contacts = props.list.map((contact,index) => {
		if(state.editIndex === index) {
			/*setState({
				...state,
	
			})*/
			return(
				<tr key={contact.id}>
					<td><input type="text"
								name="firstname"
								id="firstname"
								onChange={onChange}
								value={state.firstname}/></td>
					<td><input type="text"
								name="lastname"
								id="lastname"
								onChange={onChange}
								value={state.lastname}/></td>				
					<td><input type="email"
								name="email"
								id="email"
								onChange={onChange}
								value={state.email}/></td>
					<td><input type="tel"
								name="phone"
								id="phone"
								onChange={onChange}
								value={state.phone}/></td>
				</tr>
			)
		}
		if(state.removeIndex === index) {
			return ( <tr key={contact.id}>
				<td>{contact.firstname}</td>
				<td>{contact.lastname}</td>
				<td>{contact.email}</td>
				<td>{contact.phone}</td>
				<td><button onClick={() => cancel()}>Cancel</button></td>
				<td><button onClick={() => removeContact(contact.id)}>Confirm</button></td>
			</tr>
			)
		}
		return(
			<tr key={contact.id}>
				<td>{contact.firstname}</td>
				<td>{contact.lastname}</td>
				<td>{contact.email}</td>
				<td>{contact.phone}</td>
				<td><button onClick={() => changeToRemoveMode(index)}>Remove</button></td>
				<td><button onClick={() => changeToEditMode(index,contact)}>Edit</button></td>
			</tr>
		)
	})
	return (
		<table>
			<thead>
				<tr>	
					<th>First Name</th>
					<th>Last Name</th>
					<th>Email</th>
					<th>Phone</th>
					<th>Remove</th>
					<th>Edit</th>
				</tr>
			</thead>
			<tbody>
			{contacts}
			</tbody>
		</table>
	)

}

export default ContactList;
